const founders = [
  {
    id: '1a',
    name: 'Mark Zuckerberg',
    company: 'Meta',
    description: 'Co-founder of Meta.',
  },
  {
    id: '2b',
    name: 'Elon Musk',
    company: 'Tesla',
    description: 'CEO of Tesla, SpaceX.',
  },
  {
    id: '3c',
    name: 'Bill Gates',
    company: 'Microsoft',
    description: 'Co-founder of Microsoft.',
  },
  {
    id: '4d',
    name: 'Steve Jobs',
    company: 'Apple',
    description: 'Visionary behind Apple.',
  },
  {
    id: '5e',
    name: 'Larry Page',
    company: 'Google',
    description: 'Co-founder of Google.',
  },
  {
    id: '6f',
    name: 'Sergey Brin',
    company: 'Google',
    description: 'Google co-founder.',
  },
  {
    id: '7g',
    name: 'Jeff Bezos',
    company: 'Amazon',
    description: 'Founder of Amazon.',
  },
  {
    id: '8h',
    name: 'Jack Dorsey',
    company: 'Twitter',
    description: 'Co-founder of Twitter.',
  },
  {
    id: '9i',
    name: 'Reed Hastings',
    company: 'Netflix',
    description: 'Co-founder of Netflix.',
  },
  {
    id: '10j',
    name: 'Travis Kalanick',
    company: 'Uber',
    description: 'Uber co-founder.',
  },
  {
    id: '11k',
    name: 'Brian Chesky',
    company: 'Airbnb',
    description: 'Co-founder of Airbnb.',
  },
  {
    id: '12l',
    name: 'Evan Spiegel',
    company: 'Snapchat',
    description: 'Co-founder of Snapchat.',
  },
  {
    id: '13m',
    name: 'Stewart Butterfield',
    company: 'Slack',
    description: 'Co-founder of Slack.',
  },
  {
    id: '14n',
    name: 'Daniel Ek',
    company: 'Spotify',
    description: 'Co-founder of Spotify.',
  },
  {
    id: '15o',
    name: 'Drew Houston',
    company: 'Dropbox',
    description: 'Dropbox co-founder.',
  },
  {
    id: '16p',
    name: 'Patrick Collison',
    company: 'Stripe',
    description: 'Co-founder of Stripe.',
  },
  {
    id: '17q',
    name: 'Ben Silbermann',
    company: 'Pinterest',
    description: 'Co-founder of Pinterest.',
  },
  {
    id: '18r',
    name: 'Garrett Camp',
    company: 'Uber',
    description: 'Co-founder of Uber.',
  },
  {
    id: '19s',
    name: 'Jessica Livingston',
    company: 'Y Combinator',
    description: 'Co-founder of YC.',
  },
  {
    id: '20t',
    name: 'Max Levchin',
    company: 'PayPal',
    description: 'Co-founder of PayPal.',
  },
  {
    id: '21u',
    name: 'Paul Graham',
    company: 'Y Combinator',
    description: 'YC co-founder.',
  },
  {
    id: '22v',
    name: 'Tony Fadell',
    company: 'Nest',
    description: 'Invented the Nest thermostat.',
  },
  {
    id: '23w',
    name: 'Susan Wojcicki',
    company: 'YouTube',
    description: 'CEO of YouTube.',
  },
  {
    id: '24x',
    name: 'Kevin Systrom',
    company: 'Instagram',
    description: 'Instagram co-founder.',
  },
  {
    id: '25y',
    name: 'Mike Krieger',
    company: 'Instagram',
    description: 'Co-founder of Instagram.',
  },
  {
    id: '26z',
    name: 'Chad Hurley',
    company: 'YouTube',
    description: 'YouTube co-founder.',
  },
  {
    id: '27aa',
    name: 'Jawed Karim',
    company: 'YouTube',
    description: 'YouTube co-founder.',
  },
  {
    id: '28bb',
    name: 'Andrew Mason',
    company: 'Groupon',
    description: 'Founder of Groupon.',
  },
  {
    id: '29cc',
    name: 'Eric Yuan',
    company: 'Zoom',
    description: 'Founder of Zoom.',
  },
  {
    id: '30dd',
    name: 'Whitney Wolfe Herd',
    company: 'Bumble',
    description: 'Founder of Bumble.',
  },
  {
    id: '31ee',
    name: 'David Karp',
    company: 'Tumblr',
    description: 'Founder of Tumblr.',
  },
  {
    id: '32ff',
    name: 'Tim Sweeney',
    company: 'Epic Games',
    description: 'Founder of Epic Games.',
  },
  {
    id: '33gg',
    name: 'Richard Branson',
    company: 'Virgin',
    description: 'Founder of Virgin Group.',
  },
  {
    id: '34hh',
    name: 'Peter Thiel',
    company: 'PayPal',
    description: 'Co-founder of PayPal.',
  },
  {
    id: '35ii',
    name: 'Elie Seidman',
    company: 'Tinder',
    description: 'Former CEO of Tinder.',
  },
  {
    id: '36jj',
    name: 'Anthony Casalena',
    company: 'Squarespace',
    description: 'Founder of Squarespace.',
  },
  {
    id: '37kk',
    name: 'Adam Neumann',
    company: 'WeWork',
    description: 'Co-founder of WeWork.',
  },
  {
    id: '38ll',
    name: 'Anne Wojcicki',
    company: '23andMe',
    description: 'Co-founder of 23andMe.',
  },
  {
    id: '39mm',
    name: 'Josh Silverman',
    company: 'Etsy',
    description: 'CEO of Etsy.',
  },
  {
    id: '40nn',
    name: 'Michelle Zatlyn',
    company: 'Cloudflare',
    description: 'Co-founder of Cloudflare.',
  },
  {
    id: '41oo',
    name: 'Matthew Prince',
    company: 'Cloudflare',
    description: 'Co-founder of Cloudflare.',
  },
  {
    id: '42pp',
    name: 'Alexis Ohanian',
    company: 'Reddit',
    description: 'Co-founder of Reddit.',
  },
  {
    id: '43qq',
    name: 'Steve Huffman',
    company: 'Reddit',
    description: 'Co-founder of Reddit.',
  },
  {
    id: '44rr',
    name: 'Marc Andreessen',
    company: 'Netscape',
    description: 'Co-founder of Netscape.',
  },
  {
    id: '45ss',
    name: 'Brendan Eich',
    company: 'Mozilla',
    description: 'Creator of JavaScript.',
  },
  {
    id: '46tt',
    name: 'Jimmy Wales',
    company: 'Wikipedia',
    description: 'Co-founder of Wikipedia.',
  },
  {
    id: '47uu',
    name: 'Larry Sanger',
    company: 'Wikipedia',
    description: 'Co-founder of Wikipedia.',
  },
  {
    id: '48vv',
    name: 'Trip Hawkins',
    company: 'EA',
    description: 'Founder of Electronic Arts.',
  },
  {
    id: '49ww',
    name: 'Robert Kotick',
    company: 'Activision',
    description: 'CEO of Activision Blizzard.',
  },
  {
    id: '50xx',
    name: 'David Baszucki',
    company: 'Roblox',
    description: 'Founder of Roblox.',
  },
  {
    id: '51yy',
    name: 'Amr Awadallah',
    company: 'Cloudera',
    description: 'Co-founder of Cloudera.',
  },
  {
    id: '52zz',
    name: 'Ginni Rometty',
    company: 'IBM',
    description: 'Former CEO of IBM.',
  },
  {
    id: '53aaa',
    name: 'Daniel Zhang',
    company: 'Alibaba',
    description: 'Chairman of Alibaba.',
  },
  {
    id: '54bbb',
    name: 'Lei Jun',
    company: 'Xiaomi',
    description: 'Founder of Xiaomi.',
  },
  {
    id: '55ccc',
    name: 'Pavel Durov',
    company: 'Telegram',
    description: 'Founder of Telegram.',
  },
  {
    id: '56ddd',
    name: 'Jan Koum',
    company: 'WhatsApp',
    description: 'Co-founder of WhatsApp.',
  },
  {
    id: '57eee',
    name: 'Brian Acton',
    company: 'WhatsApp',
    description: 'Co-founder of WhatsApp.',
  },
  {
    id: '58fff',
    name: 'Tom Preston-Werner',
    company: 'GitHub',
    description: 'Co-founder of GitHub.',
  },
  {
    id: '59ggg',
    name: 'Chris Wanstrath',
    company: 'GitHub',
    description: 'Co-founder of GitHub.',
  },
  {
    id: '60hhh',
    name: 'Ryan Dahl',
    company: 'Node.js',
    description: 'Creator of Node.js.',
  },
  {
    id: '61iii',
    name: 'Linus Torvalds',
    company: 'Linux',
    description: 'Creator of Linux.',
  },
  {
    id: '62jjj',
    name: 'Guido van Rossum',
    company: 'Python',
    description: 'Creator of Python.',
  },
  {
    id: '63kkk',
    name: 'Bjarne Stroustrup',
    company: 'C++',
    description: 'Creator of C++.',
  },
  {
    id: '64lll',
    name: 'Brendan Iribe',
    company: 'Oculus',
    description: 'Co-founder of Oculus.',
  },
  {
    id: '65mmm',
    name: 'Palmer Luckey',
    company: 'Oculus',
    description: 'Co-founder of Oculus.',
  },
  {
    id: '66nnn',
    name: 'Diane Greene',
    company: 'VMware',
    description: 'Co-founder of VMware.',
  },
  {
    id: '67ooo',
    name: 'Andy Bechtolsheim',
    company: 'Sun Microsystems',
    description: 'Co-founder of Sun.',
  },
  {
    id: '68ppp',
    name: 'Scott McNealy',
    company: 'Sun Microsystems',
    description: 'Co-founder of Sun.',
  },
  {
    id: '69qqq',
    name: 'Evan Williams',
    company: 'Medium',
    description: 'Founder of Medium.',
  },
  {
    id: '70rrr',
    name: 'Biz Stone',
    company: 'Twitter',
    description: 'Co-founder of Twitter.',
  },
  {
    id: '71sss',
    name: 'Dick Costolo',
    company: 'Twitter',
    description: 'Former CEO of Twitter.',
  },
  {
    id: '72ttt',
    name: 'Craig Newmark',
    company: 'Craigslist',
    description: 'Founder of Craigslist.',
  },
  {
    id: '73uuu',
    name: 'Pierre Omidyar',
    company: 'eBay',
    description: 'Founder of eBay.',
  },
  {
    id: '74vvv',
    name: 'Sundar Pichai',
    company: 'Google',
    description: 'CEO of Google.',
  },
  {
    id: '75www',
    name: 'Satya Nadella',
    company: 'Microsoft',
    description: 'CEO of Microsoft.',
  },
]

export default founders
